###############################################################################
# Alacritty Configuration File
#
# This configuration provides a comfortable terminal experience with:
#   • Custom font settings (using Hack with fallback to Noto Sans)
#   • Defined window dimensions, title, and decorations
#   • A carefully chosen color scheme
#   • A beam-style cursor with unfocused hollow rendering
#   • Extended scrollback and faster scrolling multiplier
#   • Clipboard and search key bindings
#
# Save this file as: ~/.config/alacritty/alacritty.toml
###############################################################################

# -----------------------------------------------------------------------------
# General Options
# -----------------------------------------------------------------------------
live_config_reload = true

# -----------------------------------------------------------------------------
# Environment Variables
# -----------------------------------------------------------------------------
[env]
TERM = "xterm-256color"

# -----------------------------------------------------------------------------
# Font Configuration
# -----------------------------------------------------------------------------
[font]
# Primary font settings: family, style, and size.
normal      = { family = "Hack", style = "Regular" }
bold        = { family = "Hack", style = "Bold" }
italic      = { family = "Hack", style = "Italic" }
# Fallback fonts are used if the primary font is missing glyphs.
fallback    = ["Noto Sans"]
size        = 14.0

# -----------------------------------------------------------------------------
# Window & Terminal Settings
# -----------------------------------------------------------------------------
[window]
title         = "Alacritty"
dynamic_title = true
decorations   = "full"

[window.dimensions]
columns = 120
lines   = 30

# -----------------------------------------------------------------------------
# Color Scheme
# -----------------------------------------------------------------------------
[colors.primary]
background = "#1d1f21"
foreground = "#c5c8c6"

[colors.normal]
black   = "#1d1f21"
red     = "#cc6666"
green   = "#b5bd68"
yellow  = "#f0c674"
blue    = "#81a2be"
magenta = "#b294bb"
cyan    = "#8abeb7"
white   = "#c5c8c6"

[colors.bright]
black   = "#666666"
red     = "#d54e53"
green   = "#b9ca4a"
yellow  = "#e7c547"
blue    = "#7aa6da"
magenta = "#c397d8"
cyan    = "#70c0b1"
white   = "#eaeaea"

# -----------------------------------------------------------------------------
# Cursor Configuration
# -----------------------------------------------------------------------------
[cursor]
# Options: "Block", "Underline", or "Beam"
style            = "Beam"
unfocused_hollow = true

# -----------------------------------------------------------------------------
# Scrolling Configuration
# -----------------------------------------------------------------------------
[scrolling]
# Maximum number of lines to retain in the scrollback buffer.
history    = 1000000
# Scroll multiplier for faster scrolling.
multiplier = 3

# -----------------------------------------------------------------------------
# Key Bindings
# -----------------------------------------------------------------------------
# Note: Alacritty does not support tabs; these bindings cover common clipboard
#       and quit operations, along with search commands.
[[key_bindings]]
key    = "V"
mods   = "Control|Shift"
action = "Paste"

[[key_bindings]]
key    = "C"
mods   = "Control|Shift"
action = "Copy"

[[key_bindings]]
key    = "Q"
mods   = "Control"
action = "Quit"

[[key_bindings]]
key    = "F"
mods   = "Control"
action = "SearchForward"

[[key_bindings]]
key    = "B"
mods   = "Control"
action = "SearchBackward"

###############################################################################
# End of Configuration
###############################################################################