###############################################################################
# Alacritty Configuration File
#
# A refined Alacritty config featuring the Nord color palette, improved
# comments, and organized sections for window, scrolling, fonts, keybindings,
# and colors.
#
# Nord Theme:
#   - Background: Polar Night (#2e3440)
#   - Foreground: Snow Storm (#d8dee9)
###############################################################################

#########################
# WINDOW CONFIGURATION  #
#########################

[window]
# Window title as seen in the title bar (if applicable)
title = "Alacritty"

# Dimensions expressed in number of character columns and lines
dimensions = { columns = 120, lines = 34 }

# Padding (in pixels) around the text area
padding = { x = 8, y = 8 }

# Automatically update the window title based on the running process
dynamic_title = true

#########################
# SCROLLING SETTINGS    #
#########################

[scrolling]
# Multiplier for scrolling speed (higher value = faster scrolling)
multiplier = 3

# Maximum number of lines to retain in the scrollback buffer
history = 100000

#########################
# FONT SETTINGS         #
#########################

[font]
# Base font size in points
size = 12

# (Optional) Use bright colors when drawing bold text.
# draw_bold_text_with_bright_colors = true

[font.normal]
family = "Fira Code"
style = "Regular"

[font.bold]
family = "Fira Code"
style = "Bold"

[font.italic]
family = "Fira Code"
style = "Italic"

#########################
# SELECTION BEHAVIOR    #
#########################

[selection]
# Automatically copy selected text to the system clipboard
save_to_clipboard = true

#########################
# CURSOR SETTINGS       #
#########################

[cursor]
# Available styles: Block, Underline, Beam
style = "Block"

#########################
# KEYBINDINGS           #
#########################

# Custom keyboard shortcuts to enhance productivity.
# Note: The order of definitions does not affect behavior.
[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[[keyboard.bindings]]
key = "="
mods = "Control"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "-"
mods = "Control"
action = "DecreaseFontSize"

[[keyboard.bindings]]
key = "0"
mods = "Control"
action = "ResetFontSize"

[[keyboard.bindings]]
key = "L"
mods = "Control"
action = "ClearLogNotice"

[[keyboard.bindings]]
key = "PageUp"
mods = "Shift"
action = "ScrollPageUp"

[[keyboard.bindings]]
key = "PageDown"
mods = "Shift"
action = "ScrollPageDown"

#########################
# COLOR SCHEME          #
#########################

[colors]

  # Primary colors used for the terminal background and foreground.
  [colors.primary]
  background = "#2e3440"   # Polar Night (Nord0)
  foreground = "#d8dee9"   # Snow Storm (Nord4)

  # Cursor colors: both the text color under the cursor and the cursor itself.
  [colors.cursor]
  text   = "#2e3440"
  cursor = "#d8dee9"

  # Color used for text selection highlighting.
  [colors.selection]
  background = "#4c566a"   # A slightly lighter Polar Night

  # Standard ANSI 8 colors (normal intensity)
  [colors.normal]
  black   = "#3b4252"   # Nord1
  red     = "#bf616a"   # Aurora Red (Nord11)
  green   = "#a3be8c"   # Aurora Green (Nord14)
  yellow  = "#ebcb8b"   # Aurora Yellow (Nord13)
  blue    = "#81a1c1"   # Frost (Nord9)
  magenta = "#b48ead"   # Aurora Purple (Nord15)
  cyan    = "#88c0d0"   # Frost (Nord8)
  white   = "#e5e9f0"   # Snow Storm (Nord5)

  # Bright variants of the ANSI colors.
  [colors.bright]
  black   = "#434c5e"   # Nord2
  red     = "#bf616a"   # Aurora Red (Nord11)
  green   = "#a3be8c"   # Aurora Green (Nord14)
  yellow  = "#ebcb8b"   # Aurora Yellow (Nord13)
  blue    = "#81a1c1"   # Frost (Nord9)
  magenta = "#b48ead"   # Aurora Purple (Nord15)
  cyan    = "#8fbcbb"   # Frost (Nord7)
  white   = "#eceff4"   # Snow Storm (Nord6)